routes/web.php
<?php

use App\Http\Controllers\ClanokController;
use App\Http\Controllers\CommentController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();
//Route::get('/', [App\Http\Controllers\ClanokController::class, 'index']);
Route::get('/home/{user}', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::get('/show/{clanok}', [ClanokController::class, 'show'])->name('clanok.show');


Route::group(['middleware' => ['auth']], function () {
    Route::resource('user', UserController::class);
    Route::resource('clanok', ClanokController::class);
    Route::resource('comment', CommentController::class);
    Route::get('/user/show/{user}', [UserController::class, 'show'])->name('user.show');



    Route::get('user/{user}/delete', [UserController::class, 'destroy'])->name('user.delete');
    Route::get('clanok/{clanok}/delete', [ClanokController::class, 'destroy'])->name('clanok.delete');
    Route::get('comment/{comment}/delete', [CommentController::class, 'destroy'])->name('comment.delete');
});

app/Models/Clanok.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Notifications\Notifiable;

class Clanok extends Model
{
    use HasFactory, Notifiable;
    protected $fillable = [
        'title',
        'text',
        'user_email',
    ];
    public function user(){
        return $this->belongsTo(User::class);
    }
    public function comment(){
        return $this->hasMany(Comment::class);
    }
    public function category(){
        return $this->hasOne(Category::class);
    }
}

app/Http/Controllers/ClanokController.php
<?php

namespace App\Http\Controllers;
use Aginev\Datagrid\Datagrid;
use App\Models\Clanok;

use Illuminate\Http\Request;

class ClanokController extends Controller
{

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View|\Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $user = auth()->user();


        return view('clanok.index',['user'=>$user]);

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View|\Illuminate\Http\Response
     */
    public function create()
    {
        return view('clanok.create',['action'=>route('clanok.store'),
            'method'=>'post']);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(Request $request)
    {
        $request->validate(['title'=>'required'
            ]);
        $kategoria = $request->get('kategoria');
        $title = $request->get('title');
        $text = $request->get('text');

        $clanok =auth()->user()->clanok()->create(['title'=>$title,'text'=>$text,'user_id'=>auth()->user()->id]);
        $clanok->category()->create(['title'=>$kategoria,'clanok_id'=>$clanok->id]);
        return redirect()->route('clanok.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Clanok $clanok)
    {
        return view('clanok.show', ['clanok'=> $clanok]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View|\Illuminate\Http\Response
     */
    public function edit(Clanok $clanok)
    {

        return view('clanok.edit',['action'=> route('clanok.update', $clanok->id), 'method' => 'put', 'model' => $clanok]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update(Request $request,Clanok $clanok)
    {
        $request->validate(['title'=>'required'
            ]);

        $clanok->update($request->all());
        return redirect()->route('clanok.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\RedirectResponse
     */
    public function destroy(Clanok $clanok)
    {
        $clanok->category()->delete();
        $clanok->delete();
        $user = auth()->user()->clanok;

       # return response()->json($user, 200);

        return redirect()->route('clanok.index');
    }
}

resources/views/clanok/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">{{'Pridaj clanok'}}</div>

                    <div class="card-body">
                        @if (session('status'))
                            <div class="alert alert-success" role="alert">
                                {{ session('status') }}
                            </div>
                        @endif

                        @include('clanok.formClanok')
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/clanok/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="panel">
                    <div class="panel-heading">{{'Uprav clanok'}}</div>

                    <div class="panel-body">
                        @if (session('status'))
                            <div class="alert alert-success" role="alert">
                                {{ session('status') }}
                            </div>
                        @endif

                        @include('clanok.formClanok')
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/clanok/formClanok.blade.php
<div class="form-group text-danger">
    @foreach ($errors->all() as $error)
        {{ $error }} <br>
    @endforeach
</div>

<form method="post" action="{{ $action }}">
    @csrf
    @method($method)
    <div class="form-group " >
        <label for="title" >Titul</label>
        <input type="text" class="form-control" id="title" name="title" placeholder="Titul"value="{{old ('title', @$model->title) }}">
    </div>
    <div class="form-group " >
        <label for="title" >Kategoria</label>
        <input type="text" class="form-control" id="kategoria" name="kategoria" placeholder="Kategoria"value="{{old ('title', @$model->category->title) }}">
    </div>
    <div class="form-group">
        <label for="text">Text:</label>
        <textarea class="form-control" rows="10" id="text" name="text" >{{old ('text', @$model->text) }}</textarea>
    </div>
    <div class="form-group">
        <input type="submit" class="btn btn-primary form-control">
    </div>
</form>

resources/views/clanok/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="panel">
                    <div class="panel-heading text-center">{{ __('Moje clanky') }}</div>

                    <div class="panel-body" id="telo">
                        @if (session('status'))
                            <div class="alert alert-success" role="alert">
                                {{ session('status') }}
                            </div>
                        @endif

                            <div class="ab-3">
                                <a href="{{ route('clanok.create') }}" class="btn btn-success" role="button">Pridaj clanok</a>
                            </div>

                            <?php
                            use App\Models\Clanok;$clanok =Clanok::all();
                            ?>
                            @if($user->name == "admin")
                                @foreach($clanok as $clanky)

                                    <div class="panel panel-primary " >
                                        <div  class="panel-heading text-center">{{$clanky->title}}

                                        </div>
                                        <div  class="panel-heading text-center">{{$clanky->category->title}}

                                        </div>
                                        <div  id="description" class="panel-body text-center">{{$clanky->text}}</div>


                                    </div>
                                    <a role="button"  class="btn btn-primary " href="/blog/public/show/{{$clanky->id}}">Zobraz clanok</a>
                                    <a role="button"  class="btn btn-warning " href="/blog/public/clanok/{{$clanky->id}}/edit">Uprav clanok</a>
                                    <a role="button"  class="btn btn-danger " href="/blog/public/clanok/{{$clanky->id}}/delete" >Vymaz clanok</a>

                                @endforeach
                            @elseif($user->clanok()->count() != 0 )
                                @foreach($user->clanok as $clanky)

                                    <div class="panel panel-primary " >
                                        <div  class="panel-heading text-center">{{$clanky->title}}
                                            <div  class="panel-heading text-center">{{$clanky->category->title}}

                                            </div>
                                        </div>
                                        <div  id="description" class="panel-body text-center">{{$clanky->text}}</div>


                                    </div>
                                    <a role="button"  class="btn btn-primary " href="/blog/public/show/{{$clanky->id}}">Zobraz clanok</a>
                                    <a role="button"  class="btn btn-warning " href="/blog/public/clanok/{{$clanky->id}}/edit">Uprav clanok</a>
                                    <a role="button"  class="btn btn-danger " href="/blog/public/clanok/{{$clanky->id}}/delete" >Vymaz clanok</a>

                                @endforeach
                            @endif
                    </div>
                </div>
            </div>
        </div>
    </div>



@endsection

resources/views/clanok/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="container-fluid text-center">

        <div class="row mcontent">
            <div class="col-sm-2 bok bg-white">

            </div>
            <div class="col-sm-8 text-center pt-9">


                <div class="panel panel-primary " >
                    <div class="panel-heading text-center" >{{$clanok->title}}
                        </div>
                    <div class="panel-heading text-center" >{{$clanok->category->title}}
                    </div>
                    <div class="panel-body text-center">{{$clanok->text}}</div>

                </div>
                <div class="panel " id="pan">
                @if($clanok->comment()->count() != 0 )
                @foreach($clanok->comment as $comments)

                    <div class="panel panel-danger " >
                        <div id="title" class="panel-heading text-center">{{$comments->user->email}}</div>
                        <div  id="description" class="panel-body text-center">{{$comments->text}}</div>
                    </div>
                @endforeach
                @endif
                @auth
                </div>
                <form method="post" action="{{route('comment.store')}}" >
                    @csrf
                    {{csrf_field()}}
                    <div class="alert alert-success" role="alert"style="display: none">
                        <a href="#" class="alert-link">result.vysledok</a>
                    </div>
                    <div class="form-group" id="formular">
                        <input type="hidden" name="_token" id="_token" value="{{ Session::token() }}">
                        <label for="text">Text:</label>
                        <textarea class="form-control" rows="4" id="text" name="text" ></textarea>
                        <textarea class="form-control" rows="4" id="idcko" name="idcko" style="display:none" >{{$clanok->id}}</textarea>
                        <textarea class="form-control" rows="4" id="user" name="user"style="display:none" >{{auth()->user()->id}}</textarea>


                    </div>
                    <div class="form-group">
                        <input id="rem" type="submit" class="btn btn-primary form-control">
                    </div>
                </form>
                <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
                    <script type=text/javascript>
                        $(document).ready(function() {
                            $("#rem").click(function(e) {
                                e.preventDefault();
                                var text = $("#text").val();
                                var clanok_id = $("#idcko").val();
                                var user_id = $("#user").val();
                                var _token = $("#_token").val();
                                $.ajaxSetup({
                                    headers: {
                                        'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content'),
                                        'Content-Type': 'application/json'
                                    }
                                });
                                $.ajax({
                                    type: 'POST',
                                    url: "{{url('/comment')}}",
                                    dataType:'json',
                                    data: JSON.stringify({
                                        text:text,
                                        clanok_id:clanok_id,
                                        user_id:user_id,
                                        _token :_token
                                    }),
                                    success: function (result) {
                                        console.log(result);
                                        $(".alert").show();
                                        $(".alert").html(result.vysledok);
                                        $("#pan").load(window.location.href + " #pan" );
                                        document.getElementById("text").value = "";

                                    },
                                    error: function(){
                                        alert("error!!!!");
                                    }
                                });
                            });
                        });

                    </script>
                @endauth
            </div>

        </div>
    </div>

@endsection